-- Database: GLOBALPLA Metadata version: 2 Exported: Feb 18, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6635_WO_INFO" USING 'GCG_6635_WO_INFO.mkd' PAGESIZE=4096 (
 "PART_STATUS" CHAR(20),
 "PART_STATUS_DT_CHG" DATE,
 "PART_LINKS" BIT DEFAULT '0' NOT NULL,
 "PART_LINKS_DT_CHG" DATE,
 "DATASHEETS" BIT DEFAULT '0' NOT NULL,
 "DATASHEETS_DT_CHG" DATE,
 "MAT_REQ" BIT DEFAULT '0' NOT NULL,
 "MAT_REQ_DT_CHG" DATE,
 "FINAL_ROUTER" BIT DEFAULT '0' NOT NULL,
 "FINAL_RT_DT_CHG" DATE,
 "ROUTER_COMPLETE" BIT DEFAULT '0' NOT NULL,
 "RT_COMPLETE_DT_CHG" DATE,
 "WO_PKG" BIT DEFAULT '0' NOT NULL,
 "WO_PKG_DT_CHG" DATE,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
